import { getApiBaseUrl } from '../config';
const token=()=>String(wx.getStorageSync('consumer_session_token')||'');
export class CommerceApiError extends Error{constructor(readonly status:number){super(`Commerce API ${status}`);}}
async function request<T>(path:string,method:'GET'|'POST'|'PATCH'|'PUT'|'DELETE'='GET',data?:object):Promise<T>{const response=await new Promise<WechatMiniprogram.RequestSuccessCallbackResult>((resolve,reject)=>wx.request({url:`${getApiBaseUrl()}${path}`,method,data,header:token()?{Authorization:`Bearer ${token()}`}:{},success:resolve,fail:reject}));if(response.statusCode<200||response.statusCode>=300)throw new CommerceApiError(response.statusCode);return response.data as T;}
export type Product={id:string;name:string;description:string|null;coverUrl:string|null;title:string|null;author:string|null;isbn:string|null;publisher:string|null;skus:Array<{id:string;code:string;name:string;priceMinor:number;availableForSale:boolean}>};
export const listProducts=(q='')=>request<{products:Product[]}>(`/api/v1/catalog/products${q?`?q=${encodeURIComponent(q)}`:''}`);export const getProduct=(id:string)=>request<Product>(`/api/v1/catalog/products/${id}`);
export const getCart=()=>request<{items:Array<{id:string;skuId:string;productName:string;skuName:string;unitPriceMinor:number;quantity:number;lineTotalMinor:number;availableForSale:boolean}>;subtotalMinor:number}>('/api/v1/commerce/cart');export const addCartItem=(skuId:string,quantity=1)=>request('/api/v1/commerce/cart/items','POST',{skuId,quantity});export const updateCartItem=(id:string,quantity:number)=>request('/api/v1/commerce/cart/items/'+id,'PATCH',{quantity});export const deleteCartItem=(id:string)=>request('/api/v1/commerce/cart/items/'+id,'DELETE');
export type Address={id:string;recipientName:string;phone:string;region:string;city:string;district:string;addressLine:string;postalCode?:string|null;isDefault:boolean};export type AddressInput=Omit<Address,'id'>;export const listAddresses=()=>request<{addresses:Address[]}>('/api/v1/commerce/addresses');export const createAddress=(data:AddressInput)=>request<Address>('/api/v1/commerce/addresses','POST',data);export const updateAddress=(id:string,data:AddressInput)=>request<Address>('/api/v1/commerce/addresses/'+id,'PUT',data);export const deleteAddress=(id:string)=>request('/api/v1/commerce/addresses/'+id,'DELETE');
export const checkout=(addressId:string)=>request<{subtotalMinor:number;totalMinor:number;paymentAvailable:false;paymentMessage:string}>('/api/v1/commerce/checkout/preview','POST',{addressId});export const createOrder=(addressId:string,clientRequestId:string)=>request<{id:string;orderNumber:string;status:string;totalMinor:number}>('/api/v1/commerce/orders','POST',{addressId,clientRequestId});export const listOrders=()=>request<{orders:Array<{id:string;orderNumber:string;status:string;totalMinor:number;createdAt:string}>}>('/api/v1/commerce/orders');export const getOrder=(id:string)=>request<{id:string;orderNumber:string;status:string;totalMinor:number;items:Array<{id:string;productName:string;skuName:string;quantity:number;lineTotalMinor:number}>}>('/api/v1/commerce/orders/'+id);export const cancelOrder=(id:string)=>request('/api/v1/commerce/orders/'+id+'/cancel','POST');
