import { z } from 'zod';
import type { FastifyInstance, FastifyReply, FastifyRequest } from 'fastify';
import { addCartItemRequestSchema, addressInputSchema, adminCatalogQuerySchema, adminProductInputSchema, catalogListResponseSchema, catalogProductSchema, catalogQuerySchema, checkoutPreviewRequestSchema, checkoutPreviewResponseSchema, commerceErrorResponseSchema, createOrderRequestSchema, orderListResponseSchema, orderSchema, updateCartItemRequestSchema } from '@xiaohai/contracts/commerce';
import type { ConsumerSessionService } from '../auth/session.js';
import type { StaffAuthorizationService } from '../auth/staff-authorization.js';
import { ConsumerAuthError } from '../auth/errors.js';
import { CommerceError, type CommerceService } from './commerce-service.js';

export const CATALOG_MANAGE_PERMISSION = 'catalog.manage';
export function registerCommerceRoutes(app: FastifyInstance, options: { commerce: CommerceService; consumerSessions: ConsumerSessionService; staffAuthorization: StaffAuthorizationService }) {
  const consumerId = (request: FastifyRequest) => { const raw = request.headers.authorization; const token = raw?.startsWith('Bearer ') ? raw.slice(7) : ''; const claims = token ? options.consumerSessions.verify(token) : null; if (!claims) throw new CommerceAuthError(); return claims.consumerUserId; };
  const staff = async (request: FastifyRequest) => { const context = await options.staffAuthorization.authenticate(request.headers.authorization); options.staffAuthorization.requirePermission(context, CATALOG_MANAGE_PERMISSION); options.staffAuthorization.requireDataScope(context, 'GLOBAL', null); };
  app.get('/api/v1/catalog/products', async (request, reply) => { const input = catalogQuerySchema.safeParse(request.query); if (!input.success) return invalid(reply, request.id); try { return catalogListResponseSchema.parse(await options.commerce.listCatalog(input.data.q)); } catch (error) { return fail(request, reply, error); } });
  app.get('/api/v1/catalog/products/:id', async (request, reply) => { const params = z.object({ id: z.uuid() }).safeParse(request.params); if (!params.success) return invalid(reply, request.id); try { return catalogProductSchema.parse(await options.commerce.getProduct(params.data.id)); } catch (error) { return fail(request, reply, error); } });
  app.get('/api/v1/commerce/cart', async (request, reply) => { try { return await options.commerce.getCart(consumerId(request)); } catch (error) { return fail(request, reply, error); } });
  app.post('/api/v1/commerce/cart/items', async (request, reply) => { const input = addCartItemRequestSchema.safeParse(request.body); if (!input.success) return invalid(reply, request.id); try { return await options.commerce.addCartItem(consumerId(request), input.data.skuId, input.data.quantity); } catch (error) { return fail(request, reply, error); } });
  app.patch('/api/v1/commerce/cart/items/:id', async (request, reply) => { const params=z.object({id:z.uuid()}).safeParse(request.params); const input=updateCartItemRequestSchema.safeParse(request.body); if(!params.success||!input.success)return invalid(reply,request.id); try{return await options.commerce.updateCartItem(consumerId(request),params.data.id,input.data.quantity);}catch(error){return fail(request,reply,error);} });
  app.delete('/api/v1/commerce/cart/items/:id', async (request,reply)=>{const params=z.object({id:z.uuid()}).safeParse(request.params);if(!params.success)return invalid(reply,request.id);try{await options.commerce.deleteCartItem(consumerId(request),params.data.id);return reply.status(204).send();}catch(error){return fail(request,reply,error);}});
  app.get('/api/v1/commerce/addresses',async(request,reply)=>{try{return await options.commerce.listAddresses(consumerId(request));}catch(error){return fail(request,reply,error);}});
  app.post('/api/v1/commerce/addresses',async(request,reply)=>{const input=addressInputSchema.safeParse(request.body);if(!input.success)return invalid(reply,request.id);try{return reply.status(201).send(await options.commerce.createAddress(consumerId(request),input.data));}catch(error){return fail(request,reply,error);}});
  app.put('/api/v1/commerce/addresses/:id',async(request,reply)=>{const params=z.object({id:z.uuid()}).safeParse(request.params);const input=addressInputSchema.safeParse(request.body);if(!params.success||!input.success)return invalid(reply,request.id);try{return await options.commerce.updateAddress(consumerId(request),params.data.id,input.data);}catch(error){return fail(request,reply,error);}});
  app.delete('/api/v1/commerce/addresses/:id',async(request,reply)=>{const params=z.object({id:z.uuid()}).safeParse(request.params);if(!params.success)return invalid(reply,request.id);try{await options.commerce.deleteAddress(consumerId(request),params.data.id);return reply.status(204).send();}catch(error){return fail(request,reply,error);}});
  app.post('/api/v1/commerce/checkout/preview',async(request,reply)=>{const input=checkoutPreviewRequestSchema.safeParse(request.body);if(!input.success)return invalid(reply,request.id);try{return checkoutPreviewResponseSchema.parse(await options.commerce.checkoutPreview(consumerId(request),input.data.addressId));}catch(error){return fail(request,reply,error);}});
  app.post('/api/v1/commerce/orders',async(request,reply)=>{const input=createOrderRequestSchema.safeParse(request.body);if(!input.success)return invalid(reply,request.id);try{return reply.status(201).send(orderSchema.parse(await options.commerce.createOrder(consumerId(request),input.data.addressId,input.data.clientRequestId)));}catch(error){return fail(request,reply,error);}});
  app.get('/api/v1/commerce/orders',async(request,reply)=>{try{return orderListResponseSchema.parse(await options.commerce.listOrders(consumerId(request)));}catch(error){return fail(request,reply,error);}});
  app.get('/api/v1/commerce/orders/:id',async(request,reply)=>{const params=z.object({id:z.uuid()}).safeParse(request.params);if(!params.success)return invalid(reply,request.id);try{return orderSchema.parse(await options.commerce.getOrder(consumerId(request),params.data.id));}catch(error){return fail(request,reply,error);}});
  app.post('/api/v1/commerce/orders/:id/cancel',async(request,reply)=>{const params=z.object({id:z.uuid()}).safeParse(request.params);if(!params.success)return invalid(reply,request.id);try{return orderSchema.parse(await options.commerce.cancelOrder(consumerId(request),params.data.id));}catch(error){return fail(request,reply,error);}});
  app.get('/api/v1/staff/catalog/products',async(request,reply)=>{const input=adminCatalogQuerySchema.safeParse(request.query);if(!input.success)return invalid(reply,request.id);try{await staff(request);return await options.commerce.listAdminProducts(input.data.q,input.data.status);}catch(error){return fail(request,reply,error);}});
  app.post('/api/v1/staff/catalog/products',async(request,reply)=>{const input=adminProductInputSchema.safeParse(request.body);if(!input.success)return invalid(reply,request.id);try{await staff(request);return reply.status(201).send(await options.commerce.createAdminProduct(input.data));}catch(error){return fail(request,reply,error);}});
  app.put('/api/v1/staff/catalog/products/:id',async(request,reply)=>{const params=z.object({id:z.uuid()}).safeParse(request.params);const input=adminProductInputSchema.safeParse(request.body);if(!params.success||!input.success)return invalid(reply,request.id);try{await staff(request);return await options.commerce.updateAdminProduct(params.data.id,input.data);}catch(error){return fail(request,reply,error);}});
}
class CommerceAuthError extends Error {}
function invalid(reply:FastifyReply,requestId:string){return reply.status(400).send(commerceErrorResponseSchema.parse({error:{code:'INVALID_REQUEST',message:'Invalid request',requestId}}));}
function fail(request:FastifyRequest,reply:FastifyReply,error:unknown){let status=500;let code:'CONSUMER_AUTHENTICATION_REQUIRED'|'STAFF_AUTHENTICATION_REQUIRED'|'STAFF_FORBIDDEN'|'NOT_FOUND'|'CONFLICT'|'NOT_PURCHASABLE'|'INVALID_ORDER_STATE'|'INTERNAL_ERROR'='INTERNAL_ERROR';if(error instanceof CommerceAuthError){status=401;code='CONSUMER_AUTHENTICATION_REQUIRED';}else if(error instanceof ConsumerAuthError){status=error.statusCode;code=error.code==='STAFF_FORBIDDEN'?'STAFF_FORBIDDEN':error.code==='STAFF_AUTHENTICATION_REQUIRED'?'STAFF_AUTHENTICATION_REQUIRED':'INTERNAL_ERROR';}else if(error instanceof CommerceError){code=error.code;status=code==='NOT_FOUND'?404:code==='NOT_PURCHASABLE'?409:code==='INVALID_ORDER_STATE'?409:409;}request.log.warn({requestId:request.id,errorCode:code},'Commerce request failed');return reply.status(status).send(commerceErrorResponseSchema.parse({error:{code,message:publicMessage(code),requestId:request.id}}));}
function publicMessage(code:string){switch(code){case'CONSUMER_AUTHENTICATION_REQUIRED':return'Consumer authentication required';case'STAFF_AUTHENTICATION_REQUIRED':return'Staff authentication required';case'STAFF_FORBIDDEN':return'Forbidden';case'NOT_FOUND':return'Resource not found';case'CONFLICT':return'Commerce conflict';case'NOT_PURCHASABLE':return'SKU is not purchasable';case'INVALID_ORDER_STATE':return'Order state does not allow this action';default:return'Internal server error';}}
